app:
baseUrl: "https://bfhldevapigw.healthrx.co.in"
name: "Rashmi Rekha Sahoo"
regNo: "22BCE0710" 
email: "rashmirekhasahoo693@gmail.com"
language: "JAVA" 


spring:
datasource:
url: jdbc:h2:mem:autosolver;DB_CLOSE_DELAY=-1
driverClassName: org.h2.Driver
username: sa
password: ""
jpa:
hibernate:
ddl-auto: update
show-sql: true
h2:
console:
enabled: true
path: /h2-console
logging:
level:
root: INFO
org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
